### PR TITLE
Added a dropdown menu to make admin selection of background id more user friendly

### PR DESCRIPTION
**Pull request by andstun**

### CODE REVIEW

**Comment by aaronabraham311** [comment]
Is something wrong with the package-lock?? Why is this diff so big

**Comment by ahmedhamodi** [comment]
> Is something wrong with the package-lock?? Why is this diff so big

Fixed. Not sure why that happened, but doing `npm install` on my system reset the changes.

**Comment by aaronabraham311** [comment]
@andstun code looks great, but could you perhaps link a loom video so I can see how it functions?

**Review by ahmedhamodi — APPROVED** [review]
Code tested and looks good to me.

In the future make sure to add a loom video showing it working!

**Comment by ahmedhamodi** [comment]
Taking too long. @andstun please be quicker on responding to PR comments. It's been 3 days with a work session in that time frame.

Will merge since I tested this locally.

**Pull request merged**
